# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a38e76e485fe7afe82edc727b74ad44776d86220478ff0f1b4cd82a1b62c6638a20e3a335a9711a9c57dcf1a5ea4215aca0ef729b7fe376af22efad81367cde6

test:
  secret_key_base: 8c51e962067b4196ef525535753d646da08d445bb8758223279042e0678ebff7b42f87b664527dd00915cb31adca12d01e9d5d67df8a721a85bd785a9f9c5976

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
